# Generated by Django 2.0 on 2018-06-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180530_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.URLField(default='', verbose_name='轮播图'),
        ),
    ]
