# Generated by Django 2.0 on 2018-05-28 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseComments',
            new_name='MovieComments',
        ),
    ]
