# Generated by Django 2.0 on 2018-05-28 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mov_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='片名')),
                ('mov_times', models.IntegerField(default='', verbose_name='片场')),
                ('region', models.CharField(default='', max_length=30, verbose_name='地区')),
                ('star', models.IntegerField(default=0, verbose_name='星级')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上映时间')),
                ('play_nums', models.IntegerField(default=0, verbose_name='播放次数')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='评论数量')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='影片介绍')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Mov_Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
    ]
