# Generated by Django 2.0 on 2018-05-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20180528_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='', upload_to='movie/%Y/%m', verbose_name='封面图'),
        ),
    ]
