# Generated by Django 2.0 on 2018-05-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mov_url',
            field=models.URLField(default='', verbose_name='电影链接'),
        ),
    ]
