# Generated by Django 2.0 on 2018-05-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20180530_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='stars',
            field=models.IntegerField(verbose_name='星级'),
        ),
    ]
