# Generated by Django 2.0 on 2018-05-31 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20180530_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上映时间')),
            ],
            options={
                'verbose_name': '上映时间',
                'verbose_name_plural': '上映时间',
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='add_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.AddTime', verbose_name='上映时间'),
        ),
    ]
