# Generated by Django 2.0 on 2018-05-31 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20180531_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-add_time'], 'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
    ]
