# Generated by Django 2.0 on 2018-06-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20180531_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='stars',
            new_name='star',
        ),
    ]
