# Generated by Django 2.0 on 2018-06-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20180602_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-time'], 'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='add_time',
            new_name='time',
        ),
    ]
