# Generated by Django 2.0 on 2018-06-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20180602_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-add_time'], 'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='time',
            new_name='add_time',
        ),
    ]
